#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mSAVE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mSAVE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
cd /root
echo -e "Stopping service from DNS"
fun_stop () {
screen -ls | grep slowdns | cut -d. -f1 | awk '{print $1}' | xargs kill
sleep 1.5
}
fun_bar 'fun_stop'
echo ""
echo -e "Deleting Key & NS SlowDNS"
fun_rm () {
rm -rf /etc/rc.local; mv /etc/rc.local.bkp /etc/rc.local
rm -rf /etc/slowdns/server.key
rm -rf /etc/slowdns/server.pub
rm -rf /etc/slowdns/infons
rm -rf server.key
rm -rf server.pub
rm -rf remove-slow
sleep 1.5
}
fun_bar 'fun_rm'
echo ""
fun_revdns () {
echo "nameserver 8.8.8.8" > /etc/resolv.conf
systemctl enable systemd-resolved.service && systemctl start systemd-resolved.service &&
sleep 1.5
}
fun_bar 'fun_revdns'
echo ""
echo "  SlowDns Removing Successfully! [✔]"
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
clear
slowdns

