#!/bin/bash
echo -e "\033[1;36m THIS IS YOUR INFORMATION!\033[0m"
echo ""
echo -ne "NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "PUB_KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMMAND TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/arfprsty810/SlowDns/main/file/config/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m PUB_KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
