#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mSAVE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mSAVE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
clear
echo -e "\033[1;33mATTENTION HERE PLEASE! \033[0m"
echo ""
echo -e ""
echo -e "UNINSTALL SCRIPT SLOWDNS MANAGER"
echo -e ""
echo ""
read -p "Press [ENTER] to continue or CTRL + C to cancel"
echo ""
echo -e "   \033[0;36mUNINSTALLING ANCIENT FILES...\033[0m"
echo ""

fun_remove () {
rm -rf /bin/slowdns && rm /root/remove-slow
sleep 2
rm remove-slow && rm -rf /etc/slowdns && rm -rf server.key && rm -rf server.pub
sleep 2
rm -rf uninstall
}
fun_bar 'fun_remove'

read -p "Press [ ENTER ] to release the terminal"
echo -e "\033[0m"

