#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mSAVE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mSAVE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
clear
echo -e "\033[1;33mATTENTION HERE PLEASE! \033[0m"
echo ""
echo -e "At the end of the process it will be necessary to configure"
echo -e "again the SlowDNS service, choose the option"
echo -e "Use current key to restore your old key"
echo ""
read -p "Press [ENTER] to continue or CTRL + C to cancel"
echo ""
echo -e "   \033[0;36mREMOVING ANCIENT FILES...\033[0m"
echo ""
fun_remove () {
rm -rvf /bin/slowdns && rm -rvf /root/remove-slow
sleep 2
rm -rvf remove-slow && rm -rvf /etc/slowdns
}
fun_bar 'fun_remove'
echo ""
echo -e "   \033[0;36mUPDATING SCRIPT...\033[0m"
echo ""
fun_update () {
wget https://raw.githubusercontent.com/arfprsty810/SlowDns/main/install && chmod +x install && bash install
}

fun_bar 'fun_update'
sleep 3
echo ""
echo -e "\033[0;36mSLOWDNS SUCCESSFULLY UPDATED! [✔]\033[0m"
echo ""
sleep 3
echo -e "  \033[1;33mTO OPEN THE MENU USE: \033[1;37m\033sslowdns\033[1;33m"
echo ""
read -p "Press [ ENTER ] to release the terminal"
echo -e "\033[0m"
cd
rm -rf install
rm -rf update
clear
cd
